/**
 * gallery.mjs — the demo gallery, derived and never hand-edited.
 *
 * Each run writes its own `demos/stories/<id>/story.json`; the index is then
 * derived by reading every `story.json` on disk. That is what makes
 * `--story smoke` safe: a single-story run refreshes one story's data and
 * still renders a complete index, where a wholesale regeneration would drop
 * the rows it did not execute.
 *
 * A story's `status` is DERIVED from its beats and is never stored as its own
 * field — the campaign's standing cure for `declared-data-fails-open`: derive
 * the value from its source of truth and give the object no field to hold a
 * stale copy in.
 *
 * The gallery is both the demo and the regression report, so a red story is
 * shown red. A failing story displayed as if it passed makes the demo a lie.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

/** Derive one index row from a completed run result. */
export function storyRowFrom(result) {
  const beats = result.beats ?? [];
  const greenBeats = beats.filter((b) => b.status === 'green').length;
  // An empty story is not green: `every` is vacuously true on an empty array,
  // which would report a story that ran nothing as a passing story.
  const status = beats.length > 0 && greenBeats === beats.length ? 'green' : 'red';
  return Object.freeze({
    id: result.story.id,
    title: result.story.docs.title,
    status,
    beats: beats.length,
    greenBeats,
    clip: `${result.story.id}/story.webm`,
  });
}

const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** Render the index page. Pure — sorted by id so regeneration is stable. */
export function renderGalleryIndex(rows) {
  const sorted = [...rows].sort((a, b) => a.id.localeCompare(b.id));
  const cards = sorted
    .map(
      (r) => `  <section class="story ${esc(r.status)}">
    <h2>${esc(r.id)} — ${esc(r.title)}</h2>
    <p class="verdict ${esc(r.status)}">${esc(r.status)} · ${r.greenBeats}/${r.beats} beats green</p>
    <video src="${esc(r.clip)}" autoplay loop muted playsinline></video>
  </section>`,
    )
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Forge Studio — operator stories</title>
<style>
  body { font: 14px system-ui, sans-serif; margin: 0; padding: 2rem; background: #f7f7f8; color: #14151a; }
  .story { background: #fff; border-radius: 8px; padding: 1rem; margin-bottom: 1.5rem; border-left: 4px solid #999; }
  .story.green { border-left-color: #1a7f37; }
  .story.red { border-left-color: #cf222e; }
  .verdict.green { color: #1a7f37; }
  .verdict.red { color: #cf222e; font-weight: 600; }
  video { max-width: 100%; border-radius: 4px; }
</style>
</head>
<body>
<h1>Operator stories</h1>
<p>Generated by <code>npm run stories</code> from <code>tests/stories/</code>. Do not hand-edit —
   this page is derived from every <code>demos/stories/*/story.json</code> on disk.</p>
${cards}
</body>
</html>
`;
}

/** Write one story's data. */
export function writeStoryJson(result, root) {
  const dir = join(root, 'demos', 'stories', result.story.id);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'story.json'), `${JSON.stringify(result, null, 2)}\n`);
}

/** Read every story.json on disk and regenerate the index from all of them. */
export function regenerateGallery(root) {
  const base = join(root, 'demos', 'stories');
  const rows = [];
  if (existsSync(base)) {
    for (const entry of readdirSync(base, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const file = join(base, entry.name, 'story.json');
      if (!existsSync(file)) continue;
      rows.push(storyRowFrom(JSON.parse(readFileSync(file, 'utf8'))));
    }
  }
  mkdirSync(base, { recursive: true });
  const html = renderGalleryIndex(rows);
  writeFileSync(join(base, 'index.html'), html);
  return { rows, html };
}
