#!/usr/bin/env node
/**
 * dev-gen.mjs — renders the generated agent-dev pages under dev/ from data the
 * checkers own. dev/ is not the published site; a page there is never edited
 * by hand. `--check` regenerates in memory and exits 1 naming stale files.
 *
 *   node scripts/dev-gen.mjs           # write every dev/ page
 *   node scripts/dev-gen.mjs --check   # exit 1 if a committed page is stale
 *
 * Adding a page = one row in SOURCES: { out, render(root) -> markdown }.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DESIGNATED_UNGUARDED_FUNCTIONS } from './check-request-path-sinks-callers.mjs';

const FORGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const header = () => '<!-- GENERATED by `node scripts/dev-gen.mjs`; do not edit. -->\n';
const cell = (s) => String(s ?? '').replace(/\|/g, '/').replace(/\s+/g, ' ').trim();

// ---------------------------------------------------------------- sinks

export function renderSinks(root) {
  const base = readFileSync(join(root, 'scripts/request-path-sinks.baseline.txt'), 'utf8');
  const classes = JSON.parse(readFileSync(join(root, 'scripts/request-path-sinks.classes.json'), 'utf8'));
  const totals = new Map();
  for (const line of base.split('\n')) {
    const m = /^(\S+)\s+(\S+)\s+(\d+)\s*$/.exec(line);
    if (m) totals.set(m[1], (totals.get(m[1]) ?? 0) + Number(m[3]));
  }
  const files = [...totals.keys()].sort();
  const calls = [...totals.values()].reduce((a, b) => a + b, 0);
  const byClass = {};
  for (const f of files) {
    const c = classes[f]?.class;
    if (c) byClass[c] = (byClass[c] ?? 0) + 1;
  }
  const classified = Object.values(byClass).reduce((a, b) => a + b, 0);
  const split = Object.entries(byClass).sort().map(([k, v]) => `${k} ${v}`).join(', ');
  const rows = files.map((f) => {
    const e = classes[f];
    return `| \`${f}\` | ${totals.get(f)} | ${e?.class ?? 'unclassified'} | ${e?.guard ? `\`${cell(e.guard)}\`` : ''} | ${e?.verified ?? ''} | ${cell(e?.note)} |`;
  });
  const designated = Object.keys(DESIGNATED_UNGUARDED_FUNCTIONS).map((n) => `\`${n}\``).join(', ');
  return [
    header(),
    '# Request-path sinks',
    '',
    'A request-path sink is a filesystem or process call, in a module reachable from a bridge route or a CLI dispatch entry, whose path may derive from request data. `node scripts/check-request-path-sinks.mjs` counts them per file and fails when a count grows. To add one: run the checker, route the path through a guard, add the file\'s entry (class, guard, verified, note) to `scripts/request-path-sinks.classes.json`, then run the checker with `--write` and `node scripts/dev-gen.mjs`. The model behind the classes is `docs/explanation/security-model.md`.',
    '',
    `${files.length} files, ${calls} sink calls; ${classified} classified (${split}). Verified: exec = escape reproduced live, read = code read only, unver = never claimed safe. Designated unguarded functions (callers are counted as \`<fn>@caller\`): ${designated}.`,
    '',
    '| file | sinks | class | guard | verified | note |',
    '|---|---|---|---|---|---|',
    ...rows,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------- DOM

const SKIP_DIRS = new Set(['node_modules', '.next', 'tests', 'dist']);
function* walk(dir) {
  for (const d of readdirSync(dir, { withFileTypes: true })) {
    if (d.isDirectory()) {
      if (!SKIP_DIRS.has(d.name)) yield* walk(join(dir, d.name));
    } else if (/\.tsx?$/.test(d.name) && !/\.d\.ts$/.test(d.name)) yield join(dir, d.name);
  }
}

// `data-x="v"` / `data-x={'v'}` / `data-x={`v`}` / `'data-x': 'v'`; anything else after `=`/`:` is dynamic.
const ATTR_RE = /(?:\b|["'])(data-[a-z][a-z0-9-]*)["']?\s*[=:]\s*(?:"([^"]*)"|'([^']*)'|\{\s*(?:"([^"]*)"|'([^']*)'|`([^`$]*)`)\s*\}|(\{|[^\s"'{]))/g;

export function renderDom(root) {
  const studio = join(root, 'apps/studio');
  const attrs = new Map(); // name -> { values:Set, files:Set }
  if (existsSync(studio)) {
    for (const file of walk(studio)) {
      const rel = relative(root, file);
      const text = readFileSync(file, 'utf8');
      for (const m of text.matchAll(ATTR_RE)) {
        const lit = m[2] ?? m[3] ?? m[4] ?? m[5] ?? m[6];
        const e = attrs.get(m[1]) ?? { values: new Set(), files: new Set() };
        e.values.add(lit === undefined ? '(dynamic)' : `\`${lit}\``);
        e.files.add(rel);
        attrs.set(m[1], e);
      }
    }
  }
  const rows = [...attrs.keys()].sort().map((n) => {
    const e = attrs.get(n);
    const vals = [...e.values].sort((a, b) => (a === '(dynamic)') - (b === '(dynamic)') || a.localeCompare(b));
    return `| \`${n}\` | ${cell(vals.join(', '))} | ${[...e.files].sort().join(', ')} |`;
  });
  return [
    header(),
    '# Studio DOM contract',
    '',
    'The stories drive Studio by reading `data-*` attributes; the convention (what to mirror, how `data-page-ready` is derived, the disabled-reason and boundary rules) lives in `.claude/rules/studio-ui.md`. This page is the generated inventory of attributes and the values source gives them.',
    '',
    `It scans \`apps/studio\` .ts/.tsx outside tests with a regex, so it sees string-literal values only: a computed value is shown as (dynamic), a bare boolean attribute and an attribute built by spreading an object are not seen, and \`data-x="v"\` text inside a selector string counts as a use. ${attrs.size} attributes.`,
    '',
    '| attribute | values | files |',
    '|---|---|---|',
    ...rows,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------- driver

export const SOURCES = [
  { out: 'dev/request-path-sinks.md', render: renderSinks },
  { out: 'dev/studio-dom-contract.md', render: renderDom },
];

/** Output paths whose committed content differs from a fresh render. */
export function staleOutputs(root = FORGE_ROOT) {
  return SOURCES.filter((s) => {
    const p = join(root, s.out);
    return !existsSync(p) || readFileSync(p, 'utf8') !== s.render(root);
  }).map((s) => s.out);
}

function main(argv) {
  if (argv.includes('--check')) {
    const stale = staleOutputs();
    if (stale.length) {
      console.error(`dev-gen: STALE — run \`node scripts/dev-gen.mjs\`: ${stale.join(', ')}`);
      return 1;
    }
    console.log(`dev-gen: PASS — ${SOURCES.length} pages current`);
    return 0;
  }
  for (const s of SOURCES) {
    mkdirSync(dirname(join(FORGE_ROOT, s.out)), { recursive: true });
    writeFileSync(join(FORGE_ROOT, s.out), s.render(FORGE_ROOT));
    console.log(`dev-gen: wrote ${s.out}`);
  }
  return 0;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) process.exitCode = main(process.argv.slice(2));
