// dev-gen: the generated agent-dev pages under dev/ render from checker-owned
// data and stay current. File-scoped: node --experimental-strip-types --test scripts/dev-gen.test.ts
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

import { SOURCES, renderSinks, renderDom, staleOutputs } from './dev-gen.mjs';

const FORGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function put(root: string, rel: string, text: string): void {
  mkdirSync(dirname(join(root, rel)), { recursive: true });
  writeFileSync(join(root, rel), text);
}

function sinksFixture(): string {
  const root = mkdtempSync(join(tmpdir(), 'dev-gen-sinks-'));
  put(root, 'scripts/request-path-sinks.baseline.txt', 'apps/a.ts readFileSync 2\napps/a.ts existsSync 1\napps/b.ts spawn 1\n');
  put(
    root,
    'scripts/request-path-sinks.classes.json',
    JSON.stringify({ 'apps/a.ts': { class: 'guarded', guard: 'resolveGuardedPath', verified: 'exec', note: 'slug param' } })
  );
  return root;
}

test('renderSinks: do-not-edit header, derived counts, one row per baseline file', () => {
  const root = sinksFixture();
  try {
    const md = renderSinks(root);
    assert.match(md, /^<!-- GENERATED by `node scripts\/dev-gen\.mjs`; do not edit/);
    assert.match(md, /2 files, 4 sink calls; 1 classified \(guarded 1\)/);
    assert.match(md, /\| `apps\/a\.ts` \| 3 \| guarded \| `resolveGuardedPath` \| exec \| slug param \|/);
    assert.match(md, /\| `apps\/b\.ts` \| 1 \| unclassified \|/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('renderDom: literal values, dynamic marker, tests excluded, sorted', () => {
  const root = mkdtempSync(join(tmpdir(), 'dev-gen-dom-'));
  try {
    put(root, 'apps/studio/app/page.tsx', `<main data-page="home"><b data-state={s} data-action='go' /></main>`);
    put(root, 'apps/studio/components/X.tsx', `<i data-action="stop" data-field={\`f\`} />`);
    put(root, 'apps/studio/tests/unit/t.tsx', `<i data-only-in-tests="1" />`);
    const md = renderDom(root);
    assert.match(md, /\| `data-action` \| `go`, `stop` \| apps\/studio\/app\/page\.tsx, apps\/studio\/components\/X\.tsx \|/);
    assert.match(md, /\| `data-state` \| \(dynamic\) \|/);
    assert.match(md, /\| `data-field` \| `f` \|/);
    assert.ok(md.indexOf('`data-action`') < md.indexOf('`data-page`'));
    assert.ok(!md.includes('data-only-in-tests'));
    assert.equal(md, renderDom(root), 'deterministic');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('staleOutputs names a missing or edited page', () => {
  const root = sinksFixture();
  try {
    put(root, 'apps/studio/app/page.tsx', '<i data-page="x" />');
    const sources = SOURCES.map((s: { out: string }) => s.out);
    assert.deepEqual(staleOutputs(root), sources, 'nothing written yet: every page is stale');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('the committed dev/ pages are current', () => {
  assert.deepEqual(staleOutputs(FORGE_ROOT), []);
  const r = spawnSync(process.execPath, [join(FORGE_ROOT, 'scripts/dev-gen.mjs'), '--check'], { encoding: 'utf8' });
  assert.equal(r.status, 0, r.stderr);
});
