'use client';

import { useCallback, useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { StudioNav } from '@/components/StudioNav';
import { NotFound } from '@/components/NotFound';
import { FetchErrorState } from '@/components/FetchErrorState';
import { FilePackage } from '@/components/studio/FilePackage';
import { LibraryItemActions } from '@/components/studio/LibraryItemActions';
import { ApprovalRecordPanel } from '@/components/studio/ApprovalRecordPanel';
import {
  fetchHook,
  approveHook,
  overrideHookBlock,
  updateHook,
  deleteHook,
  revokeHookApproval,
  HOOK_LIFECYCLE_EVENTS,
  type HookDetail,
  type HookLifecycleEvent,
} from '@/lib/hook-client';
import { buildHookDetailView, type HookDetailView } from '@/lib/hook-library-view';
import { MAIN_CONTENT_ID } from '@/lib/main-landmark';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { useDocumentTitle } from '@/lib/document-title';
import { disabledAttrs } from '@/lib/disabled-reason';

// ---------------------------------------------------------------------------
// Hook detail — /hooks/[id] (R3-03-F4). Three distinct outcomes, never
// conflated (house rule: no silent fallback):
//   - 'ready'     — the hook exists and loaded as a valid definition.
//   - 'not-found' — no such id (unknown OR malformed — D-4: the bridge 404s
//                   for both, deliberately, so a fabricated 200 carrying an
//                   invented scan report is structurally impossible).
//   - 'error'     — the bridge itself could not be reached / errored.
// ---------------------------------------------------------------------------

type PageState = 'loading' | 'ready' | 'not-found' | 'error';

// ---------------------------------------------------------------------------
// entryScriptPathFrom — read a hook's entry `script:` path back out of its
// OWN hook.yaml body (already served in `detail.files`), never off a
// separate wire field. `hook.yaml` is always machine-generated by
// `yaml.dump` (packages/library/bridge-studio-hooks.ts's create/edit routes) and plain
// relative paths never need YAML quoting, so a single-line scalar match is
// exactly as reliable as a full parser would be for this one field — without
// adding a YAML parsing dependency to the client bundle just to read one
// line back off a document this page already has in full.
// ---------------------------------------------------------------------------

function entryScriptPathFrom(hookYamlBody: string): string | undefined {
  const m = hookYamlBody.match(/^script:\s*(.+?)\s*$/m);
  if (!m) return undefined;
  let raw = m[1] ?? '';
  if ((raw.startsWith('"') && raw.endsWith('"')) || (raw.startsWith("'") && raw.endsWith("'"))) {
    raw = raw.slice(1, -1);
  }
  return raw || undefined;
}

/** Mirrors hook-package.ts's `normalizeHookEntryPath` (server-side, not
 *  importable here — it lives under `orchestrator/`, which is node-only)
 *  just closely enough to match a `script: scripts//run.sh`-style path
 *  against the real file list's `scripts/run.sh`. */
function normalizeEntryPath(path: string): string {
  return path.split('/').filter((seg) => seg !== '' && seg !== '.').join('/');
}

export default function HookDetailPage() {
  const params = useParams();
  const router = useRouter();
  const id = (params?.id as string) ?? '';

  const [state, setState] = useState<PageState>('loading');
  const [detail, setDetail] = useState<HookDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  // W7-A1 (library-13): the HTTP status when the bridge ANSWERED (a 400
  // "invalid hook id" is a refusal, not an outage) — undefined when it was
  // never reached. Drives FetchErrorState's framing.
  const [errorStatus, setErrorStatus] = useState<number | undefined>(undefined);
  const [approving, setApproving] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [overrideReason, setOverrideReason] = useState('');
  // W7-B4 (library-08): edit / delete / revoke state.
  const [editing, setEditing] = useState(false);
  const [editName, setEditName] = useState('');
  const [editDescription, setEditDescription] = useState('');
  const [editOn, setEditOn] = useState<HookLifecycleEvent>('SessionEnd');
  const [editMatcher, setEditMatcher] = useState('');
  const [editScript, setEditScript] = useState('');
  const [savingEdit, setSavingEdit] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [revoking, setRevoking] = useState(false);
  const [revokeError, setRevokeError] = useState<string | null>(null);

  const load = useCallback(async (hookId: string) => {
    setState('loading');
    setActionError(null);
    const r = await fetchHook(hookId);
    if (r.ok && r.detail) {
      setDetail(r.detail);
      setState('ready');
      return;
    }
    setDetail(null);
    if (r.status === 404) {
      setState('not-found');
      return;
    }
    setError(r.error ?? 'could not load this hook');
    setErrorStatus(r.status);
    setState('error');
  }, []);

  useEffect(() => {
    if (id) void load(id);
  }, [id, load]);

  async function handleApprove() {
    setApproving(true);
    setActionError(null);
    const r = await approveHook(id);
    setApproving(false);
    if (!r.ok) {
      setActionError(r.error ?? 'approve failed');
      return;
    }
    void load(id);
  }

  async function handleOverride() {
    setApproving(true);
    setActionError(null);
    const r = await overrideHookBlock(id, overrideReason);
    setApproving(false);
    if (!r.ok) {
      setActionError(r.error ?? 'override failed');
      return;
    }
    setOverrideReason('');
    void load(id);
  }

  // ---- W7-B4 (library-08): edit / delete / revoke ------------------------

  function toggleEdit() {
    if (!editing && detail) {
      setEditName(detail.name);
      setEditDescription(detail.description);
      setEditOn(detail.on);
      setEditMatcher(detail.matcher ?? '');
      // PIN E fallout: `files` is now the WHOLE package (every real file on
      // disk), not a hardcoded hook.yaml+entry-script pair — so "the first
      // non-hook.yaml file" can now be a sourced sibling (e.g.
      // scripts/lib.sh) rather than the entry script the edit form is meant
      // to open. The route deliberately never forwards the raw `script:`
      // path on the wire (D-2, packages/library/bridge-studio-hooks.ts) — binding never
      // belongs on this transport — so the entry path is read back out of
      // the hook.yaml BODY that IS already served, the same file a human
      // reading the file-package tab would read it from. Falls back to the
      // pre-PIN-E heuristic (first non-hook.yaml file) if hook.yaml can't be
      // found or its `script:` line doesn't match any real file — defensive,
      // never a crash, and correct for every OOTB/community hook today
      // (still exactly two files).
      const hookYaml = detail.files.find((f) => f.path === 'hook.yaml');
      const entryPath = hookYaml ? entryScriptPathFrom(hookYaml.body) : undefined;
      const script =
        (entryPath !== undefined ? detail.files.find((f) => normalizeEntryPath(f.path) === normalizeEntryPath(entryPath)) : undefined) ??
        detail.files.find((f) => f.path !== 'hook.yaml');
      setEditScript(script?.body ?? '');
      setActionError(null);
    }
    setEditing((v) => !v);
  }

  async function handleSaveEdit() {
    setSavingEdit(true);
    setActionError(null);
    const r = await updateHook(id, {
      name: editName,
      description: editDescription,
      on: editOn,
      matcher: editMatcher.trim() ? editMatcher.trim() : null,
      scriptBody: editScript,
    });
    setSavingEdit(false);
    if (!r.ok) {
      setActionError(r.error ?? 'save failed');
      return;
    }
    setEditing(false);
    void load(id);
  }

  async function handleDelete() {
    setDeleting(true);
    setActionError(null);
    const r = await deleteHook(id);
    setDeleting(false);
    if (!r.ok) {
      setActionError(r.error ?? 'delete failed');
      return;
    }
    router.push('/hooks');
  }

  async function handleRevoke() {
    setRevoking(true);
    setRevokeError(null);
    const r = await revokeHookApproval(id);
    setRevoking(false);
    if (!r.ok) {
      setRevokeError(r.error ?? 'revoke failed');
      return;
    }
    void load(id);
  }

  const view = state === 'ready' && detail ? buildHookDetailView(detail) : null;

  // W7-C3 review (A-H4): per-route tab title, before the early returns.
  useDocumentTitle(detail?.name ?? id, 'Hooks');

  // W7-A4 (crosscut-27): unknown id → the ONE shared not-found treatment.
  if (state === 'not-found') {
    return <NotFound kind="hook" id={id} backHref="/hooks" backLabel="Hooks" detail="Either no hook has this id, or its definition failed to load as a valid hook." />;
  }

  return (
    <main
      id={MAIN_CONTENT_ID}
      data-page="hook-detail"
      data-hook-id={id}
      data-page-ready={state !== 'loading' ? 'true' : 'false'}
      {...(view && detail
        ? {
            'data-hook-event': view.on,
            'data-hook-verdict': view.scanVerdict,
            'data-hook-trust': view.trust,
            'data-hook-runnable': view.runnable ? 'true' : 'false',
            // PIN E: the whole-package sha256 fingerprint the approval
            // ledger pins — ABSENT while loading, on a fetch error, and for
            // an unknown id, exactly like the four siblings above; never
            // fabricated. Sourced from `detail` (not `view`, which carries
            // no `packageHash` field) — `detail` is non-null in this branch
            // by the same `state === 'ready'` guard `view` was built under.
            'data-package-hash': detail.packageHash,
          }
        : {})}
      style={{ minHeight: '100vh', background: 'var(--bg)', display: 'flex', flexDirection: 'column' }}
    >
      <StudioNav />
      <div style={{ maxWidth: 880, margin: '0 auto', padding: '32px 28px 64px', width: '100%' }}>
        <Breadcrumbs items={[{ label: 'Library', href: '/library' }, { label: 'Hooks', href: '/hooks' }, { label: detail?.name ?? id }]} />

        {state === 'loading' && (
          <div style={{ color: 'var(--dim)', fontSize: 13.5, padding: '24px 0' }}>Loading…</div>
        )}

        {state === 'error' && (
          <div style={{ marginTop: 16 }}>
            <FetchErrorState what="this hook" error={error ?? 'could not load this hook'} status={errorStatus} onRetry={() => { if (id) void load(id); }} />
          </div>
        )}

        {state === 'ready' && view && detail && (
          <>
            {/* W7-B4 (library-08): hooks gain the edit/delete half of CRUD. */}
            <div style={{ marginTop: 16 }}>
              <LibraryItemActions
                kind="hook"
                id={id}
                editing={editing}
                onToggleEdit={toggleEdit}
                onDelete={() => void handleDelete()}
                deleting={deleting}
                deleteBlockReason={
                  view.carriedByCount > 0
                    ? `still carried by ${view.carriedByCount} agent(s): ${view.carriedBy.join(', ')} — unbind it from their builders first`
                    : null
                }
                error={actionError}
              />
            </div>
            {editing && (
              <section data-component="hook-edit-form" style={{ marginTop: 14, display: 'flex', flexDirection: 'column', gap: 10, border: '1px solid var(--line)', borderRadius: 'var(--radius, 8px)', padding: '14px 16px' }}>
                <label style={{ fontSize: 12, color: 'var(--dim)' }}>
                  Name
                  <input data-field="hook-edit-name" type="text" value={editName} onChange={(e) => setEditName(e.target.value)} style={{ display: 'block', width: '100%', marginTop: 4, fontSize: 13, padding: '7px 10px', background: 'var(--bg-2)', border: '1px solid var(--line)', borderRadius: 4, color: 'var(--text)', boxSizing: 'border-box' }} />
                </label>
                <label style={{ fontSize: 12, color: 'var(--dim)' }}>
                  Description
                  <input data-field="hook-edit-description" type="text" value={editDescription} onChange={(e) => setEditDescription(e.target.value)} style={{ display: 'block', width: '100%', marginTop: 4, fontSize: 13, padding: '7px 10px', background: 'var(--bg-2)', border: '1px solid var(--line)', borderRadius: 4, color: 'var(--text)', boxSizing: 'border-box' }} />
                </label>
                <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
                  <label style={{ fontSize: 12, color: 'var(--dim)' }}>
                    Lifecycle event
                    <select data-field="hook-edit-on" value={editOn} onChange={(e) => setEditOn(e.target.value as HookLifecycleEvent)} style={{ display: 'block', marginTop: 4, fontSize: 13, padding: '7px 10px', background: 'var(--bg-2)', border: '1px solid var(--line)', borderRadius: 4, color: 'var(--text)' }}>
                      {HOOK_LIFECYCLE_EVENTS.map((ev) => (
                        <option key={ev} value={ev}>{ev}</option>
                      ))}
                    </select>
                  </label>
                  <label style={{ fontSize: 12, color: 'var(--dim)', flex: 1, minWidth: 180 }}>
                    Matcher (optional)
                    <input data-field="hook-edit-matcher" type="text" value={editMatcher} onChange={(e) => setEditMatcher(e.target.value)} style={{ display: 'block', width: '100%', marginTop: 4, fontSize: 13, padding: '7px 10px', background: 'var(--bg-2)', border: '1px solid var(--line)', borderRadius: 4, color: 'var(--text)', boxSizing: 'border-box' }} />
                  </label>
                </div>
                <label style={{ fontSize: 12, color: 'var(--dim)' }}>
                  Script (bash)
                  <textarea data-field="hook-edit-script" value={editScript} onChange={(e) => setEditScript(e.target.value)} rows={Math.min(20, Math.max(6, editScript.split('\n').length + 2))} spellCheck={false} style={{ display: 'block', width: '100%', marginTop: 4, fontFamily: 'var(--font-mono, monospace)', fontSize: 12.5, lineHeight: 1.6, padding: '10px 12px', background: 'var(--bg-2)', border: '1px solid var(--line)', borderRadius: 4, color: 'var(--text)', boxSizing: 'border-box', resize: 'vertical' }} />
                </label>
                <p style={{ fontSize: 11.5, color: 'var(--faint)', fontStyle: 'italic', margin: 0 }}>
                  Editing an approved hook drops it back to needs-review — the pinned hashes no
                  longer match, and that is the honest state.
                </p>
                <div style={{ display: 'flex', gap: 8 }}>
                  <button type="button" className="btn btn-primary btn-sm" data-action="save-hook-edit" onClick={() => void handleSaveEdit()} {...disabledAttrs(savingEdit ? 'Saving…' : !editName.trim() ? 'Give the hook a name first' : null)}>
                    {savingEdit ? 'Saving…' : 'Save changes'}
                  </button>
                  <button type="button" className="btn btn-sm" data-action="cancel-hook-edit" onClick={toggleEdit} disabled={savingEdit}>
                    Cancel
                  </button>
                </div>
              </section>
            )}
            <HookDetailBody
              view={view}
              packageHash={detail.packageHash}
              approving={approving}
              actionError={actionError}
              overrideReason={overrideReason}
              onOverrideReasonChange={setOverrideReason}
              onApprove={() => void handleApprove()}
              onOverride={() => void handleOverride()}
              revoking={revoking}
              revokeError={revokeError}
              onRevoke={() => void handleRevoke()}
            />
          </>
        )}
      </div>
    </main>
  );
}

// ---------------------------------------------------------------------------
// HookDetailBody
// ---------------------------------------------------------------------------

function HookDetailBody({
  view,
  packageHash,
  approving,
  actionError,
  overrideReason,
  onOverrideReasonChange,
  onApprove,
  onOverride,
  revoking,
  revokeError,
  onRevoke,
}: {
  view: HookDetailView;
  packageHash: string;
  approving: boolean;
  actionError: string | null;
  overrideReason: string;
  onOverrideReasonChange: (v: string) => void;
  onApprove: () => void;
  onOverride: () => void;
  revoking: boolean;
  revokeError: string | null;
  onRevoke: () => void;
}) {
  const canApprove = view.scanVerdict !== 'blocked' && view.trust === 'needs-review';
  const canOverride = view.scanVerdict === 'blocked' && view.trust === 'needs-review';
  const resolved = view.trust === 'approved' || view.trust === 'overridden';

  return (
    <div style={{ marginTop: 16, display: 'flex', flexDirection: 'column', gap: 24 }}>
      <div>
        <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 22, fontWeight: 700, color: 'var(--text)', margin: '0 0 8px' }}>
          {view.name}
        </h1>
        {view.description && (
          <p style={{ fontSize: 13.5, color: 'var(--dim)', margin: 0, maxWidth: 560, lineHeight: 1.6 }}>
            {view.description}
          </p>
        )}
        <div style={{ display: 'flex', gap: 8, marginTop: 10, flexWrap: 'wrap' }}>
          <span className="badge">{view.on}</span>
          {view.matcher && <span className="badge">{view.matcher}</span>}
        </div>
      </div>

      <section>
        <SectionLabel>Package</SectionLabel>
        <FilePackage files={view.files} />
      </section>

      {/* PIN E (2026-08-28 hostile review): the per-file + whole-package sha256
          fingerprints the approval ledger pins — the exact bytes an operator
          is approving, laid out plainly rather than buried in the file tabs
          above. Reference detail, kept visually quiet (small, monospace,
          `var(--faint)`) — the file package above is the headline, this is
          the receipt. */}
      <section data-section="package-files" data-package-file-count={view.files.length}>
        <SectionLabel>Package fingerprint</SectionLabel>
        <div style={{ border: '1px solid var(--line)', borderRadius: 'var(--radius-sm, 6px)', padding: '10px 12px', display: 'flex', flexDirection: 'column', gap: 8 }}>
          <div style={{ fontFamily: 'var(--font-mono, monospace)', fontSize: 11, color: 'var(--faint)', wordBreak: 'break-all' }}>
            {packageHash}
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
            {view.files.map((f) => (
              <div
                key={f.path}
                data-package-file={f.path}
                data-file-hash={f.hash}
                style={{ display: 'flex', justifyContent: 'space-between', gap: 12, fontFamily: 'var(--font-mono, monospace)', fontSize: 11, color: 'var(--faint)' }}
              >
                <span>{f.path}</span>
                <span style={{ wordBreak: 'break-all' }}>{f.hash}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section data-section="carried-by" data-carried-by-count={view.carriedByCount}>
        <SectionLabel>Carried by</SectionLabel>
        {view.carriedByCount === 0 ? (
          <p style={{ fontSize: 13, color: 'var(--faint)', fontStyle: 'italic', margin: 0 }}>
            Unbound — bind it from an agent&apos;s builder.
          </p>
        ) : (
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
            {view.carriedBy.map((slug) => (
              <Link key={slug} href={`/agents/${encodeURIComponent(slug)}`} data-carried-by-agent={slug} className="badge badge-agent" style={{ textDecoration: 'none' }}>
                {slug}
              </Link>
            ))}
          </div>
        )}
      </section>

      <ScanReportPanel view={view} />

      {/* W7-B4 (library-09): a RESOLVED hook renders its recorded approval
          (badge + approvedAt + override reason) plus the inverse act —
          approved and unapproved no longer look identical. */}
      {resolved && view.approval && (
        <ApprovalRecordPanel
          trust={view.trust as 'approved' | 'overridden'}
          approvedAt={view.approval.approvedAt}
          reason={view.approval.reason}
          onRevoke={onRevoke}
          revoking={revoking}
          error={revokeError}
        />
      )}

      {!resolved && (
        <section style={{ border: '1px solid var(--line)', borderRadius: 'var(--radius, 8px)', padding: '16px 18px', display: 'flex', flexDirection: 'column', gap: 12 }}>
          <SectionLabel>Approval</SectionLabel>
          {canApprove && (
            <div>
              <button type="button" className="btn btn-primary" data-action="approve-hook" onClick={onApprove} {...disabledAttrs(approving ? 'Approving…' : null)}>
                {approving ? 'Approving…' : 'Approve'}
              </button>
            </div>
          )}
          {canOverride && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              <p style={{ fontSize: 12, color: 'var(--faint)', margin: 0 }}>
                This hook is blocked — approve refuses it. Overriding is a distinct, recorded act
                that never launders the scan verdict; the hook stays flagged as blocked forever.
              </p>
              <input
                type="text"
                data-field="override-reason"
                placeholder="why are you overriding this block?"
                value={overrideReason}
                onChange={(e) => onOverrideReasonChange(e.target.value)}
                style={{ fontSize: 12.5, padding: '6px 10px', background: 'var(--bg-2)', border: '1px solid var(--line)', borderRadius: 4, color: 'var(--text)' }}
              />
              <button
                type="button"
                className="btn"
                data-action="override-hook-block"
                onClick={onOverride}
                disabled={approving || !overrideReason.trim()}
                style={{ alignSelf: 'flex-start' }}
              >
                {approving ? 'Overriding…' : 'Override block'}
              </button>
            </div>
          )}
          {actionError && <span style={{ fontSize: 12, color: '#f87171' }}>{actionError}</span>}
        </section>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// ScanReportPanel — the SECURITY SCAN panel (F2's verdict rendering)
// ---------------------------------------------------------------------------

const SEVERITY_STYLE: Record<string, React.CSSProperties> = {
  critical: { color: '#f87171', borderColor: 'rgba(248,113,113,.4)', background: 'rgba(248,113,113,.06)' },
  info: { color: 'var(--faint)', borderColor: 'var(--line-2)', background: 'rgba(255,255,255,.03)' },
};

function ScanReportPanel({ view }: { view: HookDetailView }) {
  const { scan } = view;
  return (
    <section
      data-section="scan-report"
      data-scan-verdict={scan.verdict}
      data-finding-count={scan.findingCount}
      data-critical-count={scan.criticalCount}
      style={{ border: '1px solid var(--line)', borderRadius: 'var(--radius, 8px)', padding: '16px 18px' }}
    >
      <SectionLabel>Security scan</SectionLabel>
      <p style={{ fontSize: 11.5, color: 'var(--faint)', margin: '0 0 10px', fontStyle: 'italic' }}>
        A static scan of the hook&apos;s script — verdict: <strong>{scan.verdict}</strong>. A finding
        declared in the hook&apos;s permission manifest is downgraded, never hidden.
      </p>
      {scan.findings.length === 0 ? (
        <p style={{ fontSize: 13, color: 'var(--faint)', fontStyle: 'italic', margin: 0 }}>No findings.</p>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {scan.findings.map((f, i) => (
            <div
              key={`${f.category}-${i}`}
              data-finding-category={f.category}
              data-finding-severity={f.severity}
              data-finding-declared={f.declared ? 'true' : 'false'}
              {...(f.path !== undefined ? { 'data-finding-path': f.path } : {})}
              style={{
                ...SEVERITY_STYLE[f.severity],
                border: '1px solid',
                borderRadius: 'var(--radius-sm, 6px)',
                padding: '8px 12px',
                fontSize: 12.5,
                opacity: f.declared ? 0.65 : 1,
              }}
            >
              <div style={{ fontWeight: 600, marginBottom: 2 }}>
                {f.category}{f.path !== undefined ? ` (${f.path})` : ''} — {f.severity}{f.declared ? ' (declared)' : ''}
              </div>
              <div>{f.message}</div>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 12, fontWeight: 700, color: 'var(--dim)', textTransform: 'uppercase', letterSpacing: '0.06em', margin: '0 0 8px' }}>
      {children}
    </h2>
  );
}
