"""
Integration tests: rendered terraform-module Copier template passes Terraform CLI gates.

Tests verify that files generated by 'copier copy modules/terraform-module <dst>'
pass all mandatory Terraform quality checks without requiring cloud credentials:

  - terraform fmt -check exits 0 (generated HCL is properly formatted)
  - terraform init -backend=false exits 0 (required_providers block is valid)
  - terraform validate exits 0 (configuration is syntactically and semantically correct)
  - terraform validate outputs a Success message

Prerequisites (tests are skipped automatically when either is missing):
  - copier CLI available in PATH
  - terraform CLI available in PATH

All tests fail until modules/terraform-module/ contains a valid, working Copier template.
"""

import os
import subprocess
import tempfile
import unittest


REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
TEMPLATE_DIR = os.path.join(REPO_ROOT, "modules", "terraform-module")

# Inputs used for all validation tests.  The null provider requires no credentials,
# making it suitable for CI environments without cloud access.
KNOWN_INPUTS = {
    "module_name": "integration_test_module",
    "description": "Integration test module for Terraform CLI validation",
    "author": "ci_test",
    "required_providers": "hashicorp/null:~> 3.0",
}


# ---------------------------------------------------------------------------
# Availability guards
# ---------------------------------------------------------------------------


def _copier_available() -> bool:
    """Return True if the copier CLI is on the PATH and responds to --version."""
    try:
        result = subprocess.run(
            ["copier", "--version"],
            capture_output=True,
            timeout=15,
        )
        return result.returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def _terraform_available() -> bool:
    """Return True if the terraform CLI is on the PATH and responds to 'version'."""
    try:
        result = subprocess.run(
            ["terraform", "version"],
            capture_output=True,
            timeout=15,
        )
        return result.returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def _both_tools_available() -> bool:
    """Return True only when both copier and terraform CLIs are available."""
    return _copier_available() and _terraform_available()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _render_template(dst_dir: str) -> subprocess.CompletedProcess:
    """
    Render the terraform-module template to dst_dir with KNOWN_INPUTS.

    --overwrite avoids prompts if the directory already has content.
    --defaults fills unspecified questions with their template defaults.
    """
    cmd = [
        "copier", "copy",
        "--overwrite",
        "--defaults",
    ]
    for key, value in KNOWN_INPUTS.items():
        cmd.extend(["--data", f"{key}={value}"])
    cmd.extend([TEMPLATE_DIR, dst_dir])
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        timeout=60,
    )


def _run(args: list, cwd: str, timeout: int = 60) -> subprocess.CompletedProcess:
    """Run a subprocess in the given working directory and return the completed process."""
    return subprocess.run(
        args,
        capture_output=True,
        text=True,
        cwd=cwd,
        timeout=timeout,
    )


def _terraform_init(cwd: str) -> subprocess.CompletedProcess:
    """
    Run 'terraform init -backend=false' in the given directory.

    -backend=false downloads provider plugins without configuring remote state —
    appropriate for CI environments that only need to validate HCL correctness.
    """
    return _run(
        ["terraform", "init", "-backend=false", "-no-color"],
        cwd=cwd,
        timeout=180,
    )


# ---------------------------------------------------------------------------
# terraform fmt -check
# ---------------------------------------------------------------------------


@unittest.skipUnless(
    _both_tools_available(),
    "copier and/or terraform CLI not available — skipping fmt tests",
)
class TestTerraformModuleGeneratedFormat(unittest.TestCase):
    """
    Generated Terraform files must pass 'terraform fmt -check'.

    The template is responsible for emitting properly formatted HCL.
    Formatting failures here must be fixed in the template source, not by
    having callers run 'terraform fmt' after generation.
    """

    @classmethod
    def setUpClass(cls):
        """Render the template once; all fmt tests share the output directory."""
        cls._tmp = tempfile.TemporaryDirectory()
        cls.output_dir = cls._tmp.name
        cls.render_result = _render_template(cls.output_dir)

    @classmethod
    def tearDownClass(cls):
        cls._tmp.cleanup()

    def test_template_renders_successfully_before_fmt_check(self):
        """
        'copier copy' must exit 0 before fmt checks can run.

        A render failure means the template itself is broken, not the formatting.
        """
        self.assertEqual(
            self.render_result.returncode,
            0,
            "copier copy failed — fmt tests cannot proceed:\n"
            f"STDOUT:\n{self.render_result.stdout}\n"
            f"STDERR:\n{self.render_result.stderr}",
        )

    def test_terraform_fmt_check_passes_for_generated_module_root(self):
        """
        'terraform fmt -check -recursive .' must exit 0 on the generated module root.

        Callers of 'copier copy' must receive pre-formatted HCL they can commit
        directly without running a formatter pass.
        """
        result = _run(
            ["terraform", "fmt", "-check", "-recursive", "-no-color", "."],
            cwd=self.output_dir,
        )
        self.assertEqual(
            result.returncode,
            0,
            "terraform fmt -check failed on the generated module. "
            "The template must emit properly formatted HCL.\n"
            f"Files needing formatting:\n{result.stdout}\n"
            f"Errors:\n{result.stderr}",
        )

    def test_terraform_fmt_check_passes_for_generated_examples_directory(self):
        """
        'terraform fmt -check' must also pass for examples/complete/main.tf.

        The examples are part of the module's public surface and must be
        formatted to the same standard as the module root.
        """
        examples_dir = os.path.join(self.output_dir, "examples")
        if not os.path.isdir(examples_dir):
            self.skipTest(
                "examples/ directory was not generated — "
                "test will apply once the template generates examples/"
            )
        result = _run(
            ["terraform", "fmt", "-check", "-recursive", "-no-color", "."],
            cwd=examples_dir,
        )
        self.assertEqual(
            result.returncode,
            0,
            "terraform fmt -check failed in the generated examples/ directory.\n"
            f"Files needing formatting:\n{result.stdout}\n"
            f"Errors:\n{result.stderr}",
        )


# ---------------------------------------------------------------------------
# terraform init -backend=false
# ---------------------------------------------------------------------------


@unittest.skipUnless(
    _both_tools_available(),
    "copier and/or terraform CLI not available — skipping init tests",
)
class TestTerraformModuleGeneratedInit(unittest.TestCase):
    """
    'terraform init -backend=false' must succeed on the generated module,
    confirming the required_providers block is syntactically valid and the
    provider sources are resolvable from the public Terraform registry.

    A failure here typically means the provider source or version constraint
    rendered by the template is malformed.
    """

    @classmethod
    def setUpClass(cls):
        cls._tmp = tempfile.TemporaryDirectory()
        cls.output_dir = cls._tmp.name
        _render_template(cls.output_dir)

    @classmethod
    def tearDownClass(cls):
        cls._tmp.cleanup()

    def test_terraform_init_backend_false_exits_zero_for_generated_module(self):
        """
        'terraform init -backend=false' must exit 0 for the generated module.

        This validates the required_providers block the template renders from
        the 'required_providers' copier variable.
        """
        result = _terraform_init(self.output_dir)
        self.assertEqual(
            result.returncode,
            0,
            "terraform init -backend=false failed on the generated module:\n"
            f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}",
        )


# ---------------------------------------------------------------------------
# terraform validate
# ---------------------------------------------------------------------------


@unittest.skipUnless(
    _both_tools_available(),
    "copier and/or terraform CLI not available — skipping validate tests",
)
class TestTerraformModuleGeneratedValidate(unittest.TestCase):
    """
    'terraform validate' must exit 0 after init on the generated module.

    This confirms the generated configuration is syntactically and semantically
    correct: no invalid resource types, no missing required arguments, no
    undeclared variables referenced in expressions.
    """

    @classmethod
    def setUpClass(cls):
        """Render the template and run init once; all validate tests share the state."""
        cls._tmp = tempfile.TemporaryDirectory()
        cls.output_dir = cls._tmp.name
        _render_template(cls.output_dir)
        # Init must succeed before validate can run; if it fails, validate tests
        # will produce meaningful failures rather than an obscure 'not initialised' error.
        _terraform_init(cls.output_dir)

    @classmethod
    def tearDownClass(cls):
        cls._tmp.cleanup()

    def test_terraform_validate_exits_zero_for_generated_module(self):
        """
        'terraform validate' must exit 0 — the generated configuration has no
        syntax errors, invalid resource types, or missing required arguments.
        """
        result = _run(
            ["terraform", "validate", "-no-color"],
            cwd=self.output_dir,
        )
        self.assertEqual(
            result.returncode,
            0,
            "terraform validate failed on the generated module:\n"
            f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}",
        )

    def test_terraform_validate_reports_success_message(self):
        """
        'terraform validate' must output a 'Success' message.

        This guards against the edge case where validate exits 0 but emits
        unexpected diagnostic warnings that indicate misconfigured resources.
        """
        result = _run(
            ["terraform", "validate", "-no-color"],
            cwd=self.output_dir,
        )
        combined = result.stdout + result.stderr
        self.assertIn(
            "Success",
            combined,
            "terraform validate did not output a Success message despite exit code 0:\n"
            f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}",
        )

    def test_terraform_validate_reports_no_errors(self):
        """
        'terraform validate' output must not contain 'Error:' when it exits 0.

        Distinguishes a clean validation pass from a partial result where
        some resources validated but others emitted error diagnostics.
        """
        result = _run(
            ["terraform", "validate", "-no-color"],
            cwd=self.output_dir,
        )
        if result.returncode == 0:
            self.assertNotIn(
                "Error:",
                result.stdout,
                "terraform validate exited 0 but the output contains error messages:\n"
                f"STDOUT:\n{result.stdout}",
            )

    def test_terraform_validate_on_examples_complete_exits_zero(self):
        """
        'terraform validate' must also pass for examples/complete/.

        The example must be independently valid so users can run it as a
        standalone Terraform configuration to test the module.
        """
        examples_complete = os.path.join(self.output_dir, "examples", "complete")
        if not os.path.isdir(examples_complete):
            self.skipTest(
                "examples/complete/ was not generated — "
                "test will apply once the template generates that directory"
            )
        # Init examples separately (they reference the module via relative source)
        _terraform_init(examples_complete)
        result = _run(
            ["terraform", "validate", "-no-color"],
            cwd=examples_complete,
        )
        self.assertEqual(
            result.returncode,
            0,
            "terraform validate failed in examples/complete/:\n"
            f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}",
        )


if __name__ == "__main__":
    unittest.main()
