#!/usr/bin/env node
/**
 * guard-paths — Claude Code PreToolUse hook that blocks hand edits to files
 * that must not be hand-edited.
 *
 * Input: the hook JSON on stdin, e.g.
 *   {"tool_name":"Edit","tool_input":{"file_path":"/abs/x.md"},"cwd":"…"}
 * Path field: tool_input.file_path (Write/Edit/MultiEdit) or
 * tool_input.notebook_path (NotebookEdit). Other tools are ignored.
 * Project root: env CLAUDE_PROJECT_DIR, else the JSON's cwd.
 *
 * Rules (paths are repo-relative; paths outside the project are ignored):
 *   1. docs/tutorials/** and docs/how-to/** whose CURRENT content has
 *      frontmatter containing `generated_from: <value>` are generated by the
 *      story runner — edit the story instead. New or hand-written pages pass.
 *   2. apps/docs/src/content/docs/guides/how-to/** is the generated how-to
 *      home — always blocked.
 *   3. orchestrator/, cli/, loops/, forge-ui/ at the top level were retired
 *      when the code moved into packages/* and apps/*.
 *
 * Exit codes: 0 = allow (no output). 2 = block (reason on stderr, shown to
 * Claude). Unreadable input for a guarded tool also exits 2 (fail closed).
 * No dependencies.
 */
import { readFileSync } from 'node:fs';
import { resolve, relative, isAbsolute, basename, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const GUARDED_TOOLS = new Set(['Write', 'Edit', 'MultiEdit', 'NotebookEdit']);
const RETIRED_SEGMENTS = new Set(['orchestrator', 'cli', 'loops', 'forge-ui']);
const GENERATED_DIRS = ['docs/tutorials/', 'docs/how-to/'];
const GENERATED_HOWTO_HOME = 'apps/docs/src/content/docs/guides/how-to/';

/** Value of `generated_from:` inside leading `---` frontmatter, or null. */
function generatedFrom(text) {
  const lines = text.split(/\r?\n/);
  if (lines[0]?.trim() !== '---') return null;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === '---') return null;
    const m = /^generated_from:\s*(.+?)\s*$/.exec(lines[i]);
    if (m) return m[1].replace(/^["']|["']$/g, '');
  }
  return null;
}

export function decide({ toolName, filePath, projectDir, readFile }) {
  if (!GUARDED_TOOLS.has(toolName)) return { block: false };
  const abs = resolve(projectDir, filePath);
  const rel = relative(projectDir, abs).split(sep).join('/');
  if (rel === '' || rel.startsWith('..') || isAbsolute(rel)) return { block: false };

  if (rel.startsWith(GENERATED_HOWTO_HOME)) {
    return { block: true, message: `${rel} is a generated how-to — edit the story under tests/stories/ and re-run it.` };
  }
  if (GENERATED_DIRS.some((d) => rel.startsWith(d))) {
    const text = readFile(abs);
    const from = text === null ? null : generatedFrom(text);
    if (from !== null) {
      const id = basename(from).replace(/\.story\.mjs$/, '');
      return {
        block: true,
        message: `${rel} is generated by the story runner from ${from} — edit that story file and re-run \`npm run stories -- --story ${id}\`; never hand-edit a generated page.`,
      };
    }
  }
  const segment = rel.split('/')[0];
  if (RETIRED_SEGMENTS.has(segment) && rel.includes('/')) {
    return { block: true, message: `${rel}: ${segment}/ was retired — the code lives in packages/* and apps/* now (see ARCHITECTURE.md).` };
  }
  return { block: false };
}

function readOrNull(abs) {
  try {
    return readFileSync(abs, 'utf8');
  } catch (err) {
    if (err?.code === 'ENOENT' || err?.code === 'EISDIR') return null;
    throw err;
  }
}

function failClosed(reason) {
  process.stderr.write(`guard-paths: unreadable hook input (${reason}) — refusing the edit rather than guessing\n`);
  process.exit(2);
}

function main() {
  let input;
  try {
    input = JSON.parse(readFileSync(0, 'utf8'));
  } catch (err) {
    return failClosed(`invalid JSON: ${err.message}`);
  }
  const toolName = input?.tool_name;
  if (!GUARDED_TOOLS.has(toolName)) return process.exit(0);
  const ti = input.tool_input ?? {};
  const filePath = toolName === 'NotebookEdit' ? ti.notebook_path : ti.file_path;
  if (typeof filePath !== 'string' || filePath === '') return failClosed('missing or non-string path');
  const projectDir = process.env.CLAUDE_PROJECT_DIR || (typeof input.cwd === 'string' ? input.cwd : '');
  if (!projectDir) return failClosed('no CLAUDE_PROJECT_DIR and no cwd');

  let result;
  try {
    result = decide({ toolName, filePath, projectDir, readFile: readOrNull });
  } catch (err) {
    return failClosed(`cannot inspect target: ${err.message}`);
  }
  if (result.block) {
    process.stderr.write(`${result.message}\n`);
    process.exit(2);
  }
  process.exit(0);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
